# Generated by Django 5.0.7 on 2024-08-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_subscription_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
