# Generated by Django 5.0.7 on 2024-08-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscription_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
